### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by Shelchamp** [Shelchamp/RumTumTugger#2]
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentational Components and Containers
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Demo user
- [ ] Can only see feed if logged in
- [ ] Logged in users can't see sign up / login page 
- [ ] Render errors

**Comment by Shelchamp** [comment]
Still need to clear errors when I switch components. Also still need to fix where my sign up button goes on an invalid sign up.

**Comment by wongshington** [comment]
- [ ] the sign up form should show the errors on that page instead of switching to the login form
- [ ] will need a more specific error than "Oops. There was an error. Try again."

**Comment by Shelchamp** [comment]
Pushed up my updated version to Heroku for you to check

**Comment by wongshington** [comment]
- [ ] just make the password input type password
- [ ] move the username field above the password input field on the sign up form

**Comment by wongshington** [comment]
looks guuud
